# ============================================================================
# Enterprise RAG Intelligence System
# Multi-Format Ingestion | RBAC Pre-Filtering | Cited Generation
# ============================================================================
# Author: Abhay Gupta
# GitHub: https://github.com/Abs6187
# LinkedIn: https://www.linkedin.com/in/abhay-gupta-197b17264/
# Twitter/X: https://x.com/AbhayGu19265651
# License: All Rights Reserved © 2026 Abhay Gupta
# ============================================================================

# %% [markdown]
# # 🏢 Enterprise RAG Intelligence System
# ### Author: **Abhay Gupta** | [GitHub](https://github.com/Abs6187) | [LinkedIn](https://www.linkedin.com/in/abhay-gupta-197b17264/) | [X/Twitter](https://x.com/AbhayGu19265651)
# ### Multi-Format Ingestion | RBAC Pre-Filtering | Cited Generation
# ---
# **© 2026 Abhay Gupta. All Rights Reserved.**

# %% [markdown]
# ## Step 1: Import Dependencies (No External Installs Required)

# %%
import os, json, re, math, hashlib, urllib.request, urllib.error
import pandas as pd
from pathlib import Path
from collections import Counter
from datetime import datetime

# PDF generation & parsing
from fpdf import FPDF
import fitz  # PyMuPDF

# Vector store (ChromaDB with built-in embeddings — no sentence-transformers needed)
import chromadb

print(f"[INIT] Enterprise RAG System — Built by Abhay Gupta")
print(f"[INIT] Loaded at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

# %%
# Configuration
DATA_DIR = Path("data")
CHROMA_DIR = Path("chroma_db")
ROLES_FILE = DATA_DIR / "User_Roles.json"
LOGS_FILE = DATA_DIR / "System_Logs.json"
CSV_FILE = DATA_DIR / "Financial_Records.csv"
HR_TEXT_FILE = DATA_DIR / "HR_Policy_Content.txt"
HR_PDF_FILE = DATA_DIR / "HR_Policy.pdf"

# DeepSeek API Configuration (OpenAI-compatible endpoint)
DEEPSEEK_BASE_URL = "https://api.deepseek.com/v1/chat/completions"
DEEPSEEK_MODEL = "deepseek-v4-flash"
API_KEY = os.environ.get("OPENAI_API_KEY", "")

# %% [markdown]
# ## Step 2: Generate Synthetic HR_Policy.pdf

# %%
def generate_hr_pdf(text_path: Path, pdf_path: Path):
    """Convert HR policy text file into a proper PDF document."""
    content = text_path.read_text(encoding="utf-8")
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "ACME CORPORATION", align="C")
    pdf.ln()
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, "Human Resources Policy Manual v3.2", align="C")
    pdf.ln(10)

    pdf.set_font("Helvetica", "", 9)
    for line in content.split("\n"):
        line = line.strip()
        if line.startswith("ACME CORPORATION") or line.startswith("Version 3.2"):
            continue
        if not line or all(ord(c) > 127 for c in line):
            pdf.ln(4)
            continue
        safe = ''.join(c if ord(c) < 128 else ' ' for c in line)
        if not safe.strip() or set(safe.strip()) <= {'-', '=', '_'}:
            pdf.ln(4)
            continue
        pdf.set_x(pdf.l_margin)
        if safe.startswith("SECTION"):
            pdf.set_font("Helvetica", "B", 12)
            pdf.cell(0, 7, safe)
            pdf.ln()
            pdf.set_font("Helvetica", "", 9)
        elif len(safe) > 2 and safe[0].isdigit() and "." in safe[:4]:
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, safe)
            pdf.ln()
            pdf.set_font("Helvetica", "", 9)
        else:
            pdf.write(5, safe)
            pdf.ln()

    # Add author watermark on last page
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 7)
    pdf.write(4, "Generated by Enterprise RAG System | Author: Abhay Gupta | github.com/Abs6187")

    pdf.output(str(pdf_path))
    print(f"[OK] Generated PDF: {pdf_path} ({pdf_path.stat().st_size:,} bytes)")

generate_hr_pdf(HR_TEXT_FILE, HR_PDF_FILE)

# %% [markdown]
# ## Step 3: Load User Roles (RBAC Mapping)

# %%
with open(ROLES_FILE, "r") as f:
    USER_ROLES_DB = json.load(f)

def get_user_roles(username: str) -> list:
    """Look up a user's roles from the RBAC database."""
    entry = USER_ROLES_DB.get(username)
    if entry is None:
        raise ValueError(f"Unknown user: {username}")
    return entry["roles"]

# Display user-role matrix
print("\n" + "=" * 55)
print(f"{'User':<12} {'Roles':<35} {'Clearance'}")
print("=" * 55)
for user, info in USER_ROLES_DB.items():
    print(f"{user:<12} {', '.join(info['roles']):<35} {info['clearance_level']}")

# %% [markdown]
# ## Step 4: Ingest & Tag All Data Sources
# Every chunk gets `allowed_roles` metadata for RBAC pre-filtering.

# %%
class DocumentChunk:
    """A single chunk of text with source metadata and RBAC tags."""
    def __init__(self, text, source, chunk_type, allowed_roles, extra_meta=None):
        self.text = text
        self.source = source
        self.chunk_type = chunk_type
        self.allowed_roles = allowed_roles
        self.extra_meta = extra_meta or {}
        # Generate unique chunk ID for traceability
        self.chunk_id = hashlib.md5(f"{source}:{text[:50]}".encode()).hexdigest()[:12]

    def to_metadata(self):
        meta = {
            "source": self.source,
            "chunk_type": self.chunk_type,
            "allowed_roles_str": ",".join(sorted(self.allowed_roles)),
            "chunk_id": self.chunk_id,
            "author": "Abhay Gupta",
        }
        # Store each role as an individual flag for ChromaDB filtering
        all_possible_roles = ["HR", "Admin", "Finance", "General_Employee"]
        for role in all_possible_roles:
            meta[f"role_{role}"] = "yes" if role in self.allowed_roles else "no"
        meta.update(self.extra_meta)
        return meta

# %%
def ingest_pdf(pdf_path: Path) -> list:
    """Extract text from PDF using PyMuPDF, chunk by sections."""
    doc = fitz.open(str(pdf_path))
    chunks = []
    for page_num in range(len(doc)):
        page = doc[page_num]
        text = page.get_text()
        sections = re.split(r'(SECTION \d+:.*)', text)
        for i, section in enumerate(sections):
            section = section.strip()
            if len(section) < 20:
                continue
            chunk = DocumentChunk(
                text=section,
                source=f"HR_Policy.pdf (Page {page_num + 1})",
                chunk_type="policy_document",
                allowed_roles=["HR", "Admin"],
                extra_meta={"page": str(page_num + 1)}
            )
            chunks.append(chunk)
    doc.close()
    print(f"[PDF] Ingested {len(chunks)} chunks from {pdf_path.name}")
    return chunks

# %%
def ingest_csv(csv_path: Path) -> list:
    """Convert CSV rows into tagged text chunks."""
    df = pd.read_csv(csv_path)
    chunks = []
    for _, row in df.iterrows():
        text = (
            f"{row['Quarter']} {row['Year']} | {row['Department']} ({row['Region']}): "
            f"Revenue=${row['Revenue']:,.0f}, Expenses=${row['Expenses']:,.0f}, "
            f"Net_Profit=${row['Net_Profit']:,.0f}, Growth={row['Growth_Rate']}%"
        )
        chunk = DocumentChunk(
            text=text,
            source=f"Financial_Records.csv",
            chunk_type="financial_data",
            allowed_roles=["Finance", "Admin"],
            extra_meta={
                "quarter": row["Quarter"],
                "year": str(row["Year"]),
                "department": row["Department"]
            }
        )
        chunks.append(chunk)
    # Add summary chunk accessible to General_Employee
    summary = (
        f"Financial Summary: Total Revenue across all periods = "
        f"${df['Revenue'].sum():,.0f}. Total Expenses = ${df['Expenses'].sum():,.0f}. "
        f"Overall Net Profit = ${df['Net_Profit'].sum():,.0f}."
    )
    chunks.append(DocumentChunk(
        text=summary,
        source="Financial_Records.csv (Summary)",
        chunk_type="financial_summary",
        allowed_roles=["Finance", "Admin", "General_Employee"],
    ))
    print(f"[CSV] Ingested {len(chunks)} chunks from {csv_path.name}")
    return chunks

# %%
def ingest_json_logs(json_path: Path) -> list:
    """Parse system logs and tag with their embedded RBAC roles."""
    with open(json_path, "r") as f:
        logs = json.load(f)
    chunks = []
    for log in logs:
        text = (
            f"[{log['timestamp']}] {log['severity']} | {log['service']} | "
            f"{log['error_code']}: {log['message']}"
        )
        chunk = DocumentChunk(
            text=text,
            source="System_Logs.json",
            chunk_type="system_log",
            allowed_roles=log["allowed_roles"],
            extra_meta={
                "severity": log["severity"],
                "service": log["service"],
                "error_code": log["error_code"]
            }
        )
        chunks.append(chunk)
    print(f"[JSON] Ingested {len(chunks)} chunks from {json_path.name}")
    return chunks

# %%
# Run full ingestion pipeline
all_chunks = []
all_chunks.extend(ingest_pdf(HR_PDF_FILE))
all_chunks.extend(ingest_csv(CSV_FILE))
all_chunks.extend(ingest_json_logs(LOGS_FILE))

print(f"\n{'='*50}")
print(f"Total chunks ingested: {len(all_chunks)}")
print(f"Chunk types: {Counter(c.chunk_type for c in all_chunks)}")

# %% [markdown]
# ## Step 5: Build ChromaDB Vector Store
# Uses ChromaDB's built-in default embedding function (no sentence-transformers needed).

# %%
# Initialize ChromaDB with default embeddings (uses onnxruntime internally)
client = chromadb.Client()  # In-memory for demo

# Delete collection if exists (for re-runs)
try:
    client.delete_collection("enterprise_rag")
except:
    pass

collection = client.create_collection(
    name="enterprise_rag",
    metadata={"hnsw:space": "cosine"}
)

# Add all chunks to the vector store
ids = [f"chunk_{i}" for i in range(len(all_chunks))]
documents = [c.text for c in all_chunks]
metadatas = [c.to_metadata() for c in all_chunks]

collection.add(ids=ids, documents=documents, metadatas=metadatas)
print(f"[ChromaDB] Loaded {collection.count()} chunks into vector store")

# %% [markdown]
# ## Step 6: RBAC-Filtered Retrieval

# %%
def rbac_retrieve(query: str, username: str, top_k: int = 5) -> dict:
    """
    Retrieve documents filtered by the user's RBAC roles.
    This is PRE-FILTERING: unauthorized data never enters the context.
    """
    user_roles = get_user_roles(username)

    # Build OR filter using role flag fields (role_HR, role_Finance, etc.)
    role_filters = []
    for role in user_roles:
        role_filters.append({f"role_{role}": {"$eq": "yes"}})

    if len(role_filters) == 1:
        where_filter = role_filters[0]
    else:
        where_filter = {"$or": role_filters}

    results = collection.query(
        query_texts=[query],
        n_results=top_k,
        where=where_filter,
        include=["documents", "metadatas", "distances"]
    )

    return {
        "query": query,
        "username": username,
        "roles": user_roles,
        "documents": results["documents"][0],
        "metadatas": results["metadatas"][0],
        "distances": results["distances"][0],
    }

# %% [markdown]
# ## Step 7: Citation-Aware Prompt Construction

# %%
def build_cited_prompt(query: str, retrieved: dict) -> str:
    """Build a prompt with numbered context citations."""
    context_blocks = []
    for i, (doc, meta, dist) in enumerate(zip(
        retrieved["documents"], retrieved["metadatas"], retrieved["distances"]
    ), 1):
        similarity = 1 - dist  # cosine distance to similarity
        context_blocks.append(
            f"Context ID [{i}] (Source: {meta['source']}, "
            f"Type: {meta['chunk_type']}, Similarity: {similarity:.3f}):\n{doc}"
        )

    context_text = "\n\n".join(context_blocks)

    prompt = f"""You are an Enterprise RAG assistant built by Abhay Gupta (github.com/Abs6187). Answer the user's question using ONLY the provided context below. Follow these rules strictly:

1. Use ONLY information from the provided context chunks.
2. Cite your sources using inline tags like [1], [2], etc.
3. If the answer cannot be found in the context, state: "Information not accessible or unavailable for your role."
4. List the key facts from the context before synthesizing your final answer.

--- RETRIEVED CONTEXT ---
{context_text}
--- END CONTEXT ---

User Role: {retrieved['roles']}
User Question: {query}

Answer (with citations):"""

    return prompt

# %% [markdown]
# ## Step 8: Confidence Scoring

# %%
def compute_confidence(retrieved: dict) -> dict:
    """Compute retrieval confidence metrics."""
    distances = retrieved["distances"]
    similarities = [1 - d for d in distances]

    avg_sim = sum(similarities) / len(similarities) if similarities else 0
    max_sim = max(similarities) if similarities else 0
    min_sim = min(similarities) if similarities else 0

    # Retrieval confidence tier
    if avg_sim >= 0.5:
        tier = "HIGH"
    elif avg_sim >= 0.3:
        tier = "MEDIUM"
    else:
        tier = "LOW"

    return {
        "avg_similarity": round(avg_sim, 4),
        "max_similarity": round(max_sim, 4),
        "min_similarity": round(min_sim, 4),
        "num_results": len(distances),
        "confidence_tier": tier,
    }

# %% [markdown]
# ## Step 9: LLM Generation via DeepSeek API (with Offline Fallback)
# Uses DeepSeek V4 Flash via OpenAI-compatible endpoint. No `openai` package needed — raw HTTP calls.

# %%
def call_deepseek_api(prompt: str) -> str:
    """Call DeepSeek API using raw urllib (no openai package dependency)."""
    payload = json.dumps({
        "model": DEEPSEEK_MODEL,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.1,
        "max_tokens": 800,
        "stream": False,
    }).encode("utf-8")

    req = urllib.request.Request(
        DEEPSEEK_BASE_URL,
        data=payload,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {API_KEY}",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            return data["choices"][0]["message"]["content"]
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        print(f"[DeepSeek] HTTP {e.code}: {body[:200]}")
        raise
    except Exception as e:
        print(f"[DeepSeek] Request failed: {e}")
        raise


def generate_answer_offline(prompt: str, retrieved: dict) -> str:
    """Rule-based fallback when no API key is available."""
    docs = retrieved["documents"]
    metas = retrieved["metadatas"]
    query_lower = retrieved["query"].lower()

    answer_parts = ["Based on the retrieved documents:\n"]
    for i, (doc, meta) in enumerate(zip(docs, metas), 1):
        doc_lower = doc.lower()
        query_words = set(query_lower.split())
        overlap = sum(1 for w in query_words if w in doc_lower)
        if overlap >= 1:
            sentences = [s.strip() for s in doc.split(".") if len(s.strip()) > 20]
            if sentences:
                best = max(sentences, key=lambda s: sum(1 for w in query_words if w in s.lower()))
                answer_parts.append(f"- {best.strip('.')}. [{i}]")

    if len(answer_parts) == 1:
        answer_parts.append("Information not accessible or unavailable for your role.")

    answer_parts.append(f"\n\nSources: " + ", ".join(
        f"[{i+1}] {m['source']}" for i, m in enumerate(metas)
    ))
    return "\n".join(answer_parts)


def generate_answer(prompt: str, retrieved: dict) -> str:
    """Try DeepSeek API first, fall back to offline generation."""
    if API_KEY and not API_KEY.startswith("sk-your"):
        try:
            return call_deepseek_api(prompt)
        except Exception as e:
            print(f"[LLM] DeepSeek API failed: {e}. Using offline fallback.")

    print("[LLM] No API key configured. Using offline rule-based generation.")
    return generate_answer_offline(prompt, retrieved)

# %% [markdown]
# ## Step 10: Complete Query Pipeline

# %%
def query_with_rbac(username: str, question: str, top_k: int = 5, verbose: bool = True) -> dict:
    """Full RAG pipeline: authenticate -> retrieve -> generate -> cite.
    
    Built by Abhay Gupta (github.com/Abs6187)
    """

    print(f"\n{'='*70}")
    print(f"  USER: {username} | ROLES: {get_user_roles(username)}")
    print(f"  QUERY: {question}")
    print(f"{'='*70}")

    # 1. RBAC-filtered retrieval
    retrieved = rbac_retrieve(question, username, top_k)

    # 2. Confidence scoring
    confidence = compute_confidence(retrieved)

    # 3. Build cited prompt
    prompt = build_cited_prompt(question, retrieved)

    # 4. Generate answer
    answer = generate_answer(prompt, retrieved)

    # 5. Display results
    if verbose:
        print(f"\n  Confidence: {confidence['confidence_tier']} "
              f"(avg_sim={confidence['avg_similarity']:.3f})")
        print(f"  Retrieved {confidence['num_results']} chunks\n")
        print(f"  ANSWER:\n  {'-'*60}")
        for line in answer.split("\n"):
            print(f"  {line}")
        print(f"  {'-'*60}")
        print(f"\n  Retrieved Sources:")
        for i, meta in enumerate(retrieved["metadatas"], 1):
            sim = 1 - retrieved["distances"][i-1]
            print(f"    [{i}] {meta['source']} ({meta['chunk_type']}) "
                  f"sim={sim:.3f}")

    return {
        "username": username,
        "question": question,
        "answer": answer,
        "confidence": confidence,
        "sources": retrieved["metadatas"],
        "prompt": prompt,
    }

# %% [markdown]
# ## Demo: RBAC Access Control in Action

# %% [markdown]
# ### Demo 1: Alice (HR + Admin) — Can access HR policies

# %%
result_alice = query_with_rbac("Alice", "How many PTO days do senior employees get per year?")

# %% [markdown]
# ### Demo 2: Bob (Finance) — Can access financial data

# %%
result_bob = query_with_rbac("Bob", "What was the total revenue for Sales in Q3 2025?")

# %% [markdown]
# ### Demo 3: Charlie (General Employee) — Restricted access

# %%
result_charlie = query_with_rbac("Charlie", "Show me the payroll error logs")

# %% [markdown]
# ### Demo 4: Diana (HR + Finance + Admin) — Full access

# %%
result_diana = query_with_rbac("Diana", "Summarize the latest system errors and HR policy on parental leave")

# %% [markdown]
# ### Demo 5: RBAC Security Verification
# Bob (Finance only) tries to access HR data — should be blocked.

# %%
result_bob_hr = query_with_rbac("Bob", "What is the parental leave policy?")

# %% [markdown]
# ## Summary & Confidence Matrix

# %%
print("\n" + "=" * 75)
print("  CONFIDENCE MATRIX  -  All Demo Queries")
print(f"  System by Abhay Gupta | github.com/Abs6187")
print("=" * 75)
print(f"  {'User':<10} {'Tier':<8} {'Avg Sim':<10} {'#Chunks':<10} {'Query Preview'}")
print("-" * 75)
for name, res in [("Alice", result_alice), ("Bob", result_bob),
                   ("Charlie", result_charlie), ("Diana", result_diana),
                   ("Bob(HR)", result_bob_hr)]:
    c = res["confidence"]
    q = res["question"][:40]
    print(f"  {name:<10} {c['confidence_tier']:<8} {c['avg_similarity']:<10.4f} "
          f"{c['num_results']:<10} {q}...")
print("=" * 75)
print(f"\n[DONE] Enterprise RAG Intelligence System")
print(f"[AUTHOR] Abhay Gupta | https://github.com/Abs6187")
print(f"[LICENSE] All Rights Reserved (c) 2026 Abhay Gupta")
